### PR TITLE
SYNPY-849 Use 'Deprecated' package instead of 'Deprecation'

### PR DESCRIPTION
**Pull request by thomasyu888**

### CODE REVIEW

**Comment by thomasyu888** [comment]
How do we convey that our travis job ran to completion?

**Comment by kimyen** [comment]
> How do we convey that our travis job ran to completion?

I can navigate to your fork > branch > commit > checkmark that links to your travis build. 
It looks like your travis build is good. But I do not see your appveyor build.

**Comment by thomasyu888** [comment]
What is a appveyor build?

**Comment by kimyen** [comment]
> What is a appveyor build?

Travis can build your code on Linux and MacOS environment. Appveyor can build your code on Windows environment.

**Comment by thomasyu888** [comment]
How do I set this up?

**Comment by kimyen** [comment]
> How do I set this up?

I put the link to the instructions on the previous comment.

**Comment by thomasyu888** [comment]
Ahh sorry! Thanks for the link.  Was on my phone so didn't notice.

**Comment by thomasyu888** [comment]
The appveyor seems to be failing for some reason...

**Comment by kimyen** [comment]
Looks good! Thanks @thomasyu888 !

**Pull request merged**
